Omarketplace/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from core.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('core.urls')),
    path('items/',include('item.urls')),
    path('inbox/',include('chat.urls',namespace='chat')),
    path('dashboard/',include('dashboard.urls')),
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT) # Never use this in production

chat/urls.py
from django.urls import path
from .views import *

app_name = 'chat'

urlpatterns = [
    path('new/<int:item_pk>/',new_chat,name='new'),
]

item/urls.py
from django.urls import path
from .views import *

app_name = 'item'

urlpatterns = [
    path('',items,name='items'),
    path('new/',newItem,name='newitem'),
    path('<int:pk>/',detail,name='detail'),
    path('<int:pk>/delete/',delete,name='delete'),
    path('<int:pk>/edit/',editItem,name='edit'),
]

item/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length= 50,null=False,blank=False)
    
    class  Meta:
        ordering = ['name',]
        verbose_name_plural = "Categories"

    def __str__(self):
        return self.name

class Item(models.Model):
    category = models.ForeignKey(Category,related_name='items',on_delete=models.CASCADE)
    name = models.CharField(max_length=60,null=False,blank=False)
    description = models.TextField(null=False,blank=True)
    image = models.ImageField(upload_to='item_images',blank=False,null=False)
    price = models.DecimalField(max_digits=10,decimal_places=2)
    is_sold = models.BooleanField(default=False)
    created_by = models.ForeignKey(User,related_name='items',on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['name',]

    def __str__(self):
        return self.name

item/forms.py
from django import forms

from .models import Item
INPUT_CLASSES = 'w-full py-4 px-6 rounded-xl border'

class NewItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ('category','name','description','image','price',)
        widgets = {
            'category': forms.Select(attrs={
            'class': INPUT_CLASSES
            }),
            'name': forms.TextInput(attrs={
            'class': INPUT_CLASSES
            }),
            'description': forms.Textarea(attrs={
            'class': INPUT_CLASSES
            }),
            'image': forms.FileInput(attrs={
            'class': INPUT_CLASSES
            }),
            'price': forms.TextInput(attrs={
            'class': INPUT_CLASSES
            }),
        }

class EditItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ('name','description','image','price','is_sold',)
        widgets = {
            'name': forms.TextInput(attrs={
            'class': INPUT_CLASSES
            }),
            'description': forms.Textarea(attrs={
            'class': INPUT_CLASSES
            }),
            'image': forms.FileInput(attrs={
            'class': INPUT_CLASSES
            }),
            'price': forms.TextInput(attrs={
            'class': INPUT_CLASSES
            }),
        }

item/views.py
from django.shortcuts import render,get_object_or_404,redirect
from .models import Item
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from .forms import *
from .models import *

# Create your views here.
def items(request):
    query = request.GET.get('query','')
    category_id = request.GET.get('category',0)
    categories = Category.objects.all()
    items = Item.objects.filter(is_sold=False)

    if category_id:
        items = items.filter(category_id=category_id)

    if query:
        items = items.filter(Q(name__icontains=query) | Q(description__icontains=query))

    return render(request,'item/items.html',{
        'items':items,
        'query':query,
        'categories':categories,
        'category_id':int(category_id),
    })

def detail(request,pk):
    item = get_object_or_404(Item,pk=pk)
    related_items = Item.objects.filter(category = item.category,is_sold=False).exclude(pk=pk)[0:4]
    return render(request,'item/detail.html',
                {
            'item':item,
            'related_items': related_items
                })

@login_required
def newItem(request):
    if request.method == "POST":
        form = NewItemForm(request.POST,request.FILES)

        if form.is_valid():
            item = form.save(commit=False)
            item.created_by = request.user
            item.save()

            return redirect('item:detail',pk=item.id)
    else:
        form = NewItemForm() 

    return render(request,'item/form.html',{
        'form':form,
        'title': "New item",
    })

@login_required
def editItem(request,pk):
    item = get_object_or_404(Item,pk=pk,created_by=request.user)
    if request.method == "POST":
        form = EditItemForm(request.POST,request.FILES,instance = item)

        if form.is_valid():
            form.save()

            return redirect('item:detail',pk=item.id)
    else:
        form = EditItemForm(instance = item) 

    return render(request,'item/form.html',{
        'form':form,
        'title': "Edit item",
    })


@login_required
def delete(request,pk):
    item = get_object_or_404(Item,pk=pk,created_by=request.user)
    item.delete()
    return redirect('dashboard:dashboard')

item/templates/item/detail.html
{% extends 'core/base.html' %}

{%block title%} {{item.name}} {%endblock title%}

{% block content %}

    <div class = "grid grid-cols-5 gap-6">

        <div class = "col-span-3">
            <img src = "{{ item.image.url }}" class = "rounded-xl">
        </div>

        <div class = "col-span-2 p-6 bg-gray-100 rounded-xl">

            <h1 class = "text-center mb-6 text-3xl">{{item.name}} </h1>

            <p class = " text-gray-500 text-xl"><strong> Price : </strong> INR {{item.price}}</p>
            
            {% if item.description %}
                <p class = "text-gray-700 text-2xl mt-5">
                    <strong> Description : </strong> <br> {{item.description}}
                </p>
            {% endif %}

            <p class = "text-2xl mt-10 text-gray-500"><strong> Seller : </strong> {{item.created_by.username}}</p>
            
            {% if request.user == item.created_by %}
                <div class = "mt-6 p-6 bg-white rounded-xl">
                    <p>This is your item!!</p>
                    <a href = "{% url 'item:edit' item.id %}" class = "inline-block my-6 px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl">Edit</a>
                    <a href = "{% url 'item:delete' item.id%}" class = "inline-block my-6 px-6 py-3 text-lg font-semibold bg-red-500 text-white rounded-xl">Delete</a>
                </div>
            {% else %}
                <a href="#" class = "inline-block mt-6 px-6 py-3 text-lg font-semibold rounded-xl bg-teal-500 text-white hover:bg-teal-700"> Contact Seller
                </a>
            {% endif %}
        </div>
    </div>

    <div class = "mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-2xl text-center">
            Related items
        </h2>

        <div class="grid grid-cols-3 gap-3">
                {% for item in related_items %}
                    {% if category.items.count == 1 %} <!-- This is not working right now -->
                        <p class="text-2xl text-white">There are no related items</p>
                    {% else %}
                        <div>
                            <a href="{% url 'item:detail' item.id %}">
                        <div>
                            <img src = "{{ item.image.url }}" class = "rounded-t-xl hover:scale-105 transition-all duration-300">
                        </div>
                            <div class="p-6 bg-white rounded-b-xl">
                            <h2 class="text-2xl">{{item.name}}</h2>
                            <p class="text-gray-500">Price : {{item.price}}</p>
                            </div>
                            </a>
                        </div>
                    {% endif %}
                {% endfor %}
            </div>
        </div>
{% endblock content %}

item/templates/item/form.html
{% extends 'core/base.html' %}

{%block title%} New Item {%endblock title%}

{% block content %}
    <h1 class = "mb-6 text-3xl"> {{title}} </h1>

    <form method = "post" action = "." enctype = "multipart/form-data">
        {% csrf_token %}

        <div class = "space-y-4">
            {{form.as_p}}
        </div>

        {% if form.errors or form.non_field_errors %}
            <div class="mb-3 p-6 bg-red-100 rounded-xl">
                {% for field in form %}
                    {{field.errors}} 
                {% endfor %}
                
                {{form.non_field_errors}}
            </div>
        {% endif %}
            <div class = "text-center">
                <button class="mt-6 py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 text-white rounded-xl ">Submit</button>
            </div>
    </form>
{% endblock content %}

item/templates/item/items.html
{% extends 'core/base.html' %}

{%block title%} Items {%endblock title%}

{% block content %}
    <div class = "pb-6 grid grid-cols-4 gap-4 bg-gray-100">
        <div class = "col-span-1"> 
            <form method="get" action = "{% url 'item:items' %}">
            <input name = 'query' class = 'm-1.5 w-full py-4 px-6 border rounded-xl' type = 'text' value = "{{query}}" placeholder = "Find the items">
            <button class ="bg-teal-500 text-white m-2 py-4 px-8 text-lg rounded-xl">Search </button>
            </form>
            <hr class='my-6'>

            <p class = 'font-semibold'>Categories</p>
            
            <ul>
                {% for category in categories %}
                    <li class= "py-2 px-2 rounded-xl {% if category.id == category_id %} bg-gray-200 {% endif %}">
                        <a href = "{% url 'item:items' %}? query = {{query}}&category = {{category.id}}">{{category.name}}</a>
                    </li>
                {%endfor%}
            </ul>
             <hr class='my-6'>

            <p class = 'text-center font-semibold text-xl m-2 '>Clear filters :</p>
            <ul>
                <li class = "text-center"><a href = "{% url 'item:items' %}" class = "mt-4 py-4 px-8 inline-block bg-yellow-500 text-lg rounded-xl text-white">Clear</a></li>
            </ul>
        </div>

        <div class = "col-span-3">
            <div class="grid grid-cols-3 gap-3">
            {% for item in items %}
            <div>
                <a href="{% url 'item:detail' item.id %}">
                    <div>
                        <img src = "{{item.image.url}}" class = "rounded-t-xl hover:scale-105 transition-all duration-300">
                    </div>
                    <div class="p-6 bg-white rounded-b-xl">
                        <h2 class="text-2xl">{{item.name}}</h2>
                        <p class="text-gray-500">Price : {{item.price}}</p>
                    </div>
                </a>
            </div>
            {% endfor %}
        </div>
        </div>
    </div>
{% endblock content %}